[workspace]
members = ["apps", "builder", "kernel"]
resolver = "2"
default-members = ["builder"]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
codegen-units = 1

[profile.release.package.apps]
opt-level = 0
