[workspace]
members = ["apps/*", "builder", "kernel"]
resolver = "2"
default-members = ["builder"]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1

[workspace.dependencies]
std = { path = "apps/std" }
