[workspace]
members = ["apps/*", "builder", "kernel"]
resolver = "2"
default-members = ["builder"]

[profile.release]
lto = "thin"
panic = "abort"

[profile.release.package.kernel]
opt-level = "z"
strip = true

[workspace.dependencies]
std = { path = "apps/std" }
