cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-unknown-none"

[dependencies]
x86_64 = "0.15.1"
spin = "0.9.8"
uart_16550 = "0.3.0"
pc-keyboard = "0.7.0"
bootloader_api = "0.11.7"
acpi = "5.0.0"
x2apic = "0.4.3"
bitflags = "2.5.0"
good_memory_allocator = "0.1.7"
vte = "0.13.0"

[dependencies.conquer-once]
version = "0.4.0"
default-features = false

[dependencies.time]
version = "0.3.36"
default-features = false

[dependencies.crossbeam-queue]
version = "0.3.11"
features = ["alloc"]
default-features = false

[dependencies.object]
version = "0.35.0"
features = ["read_core", "elf", "unaligned"]
default-features = false

[dependencies.noto-sans-mono-bitmap]
version = "0.3.0"
features = ["bold", "size_16", "unicode-basic-latin"]
default-features = false

[dependencies.log]
version = "0.4.21"
default-features = false
