cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-unknown-none"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
codegen-units = 1

[dependencies]
x86_64 = "0.14.11"
spin = "0.9.8"
uart_16550 = "0.3.0"
pc-keyboard = "0.7.0"
bootloader_api = "0.11.6"
acpi = "5.0.0"
x2apic = "0.4.3"
bitflags = "2.4.2"
good_memory_allocator = "0.1.7"

[dependencies.crossbeam-queue]
version = "0.3.11"
features = ["alloc"]
default-features = false

[dependencies.conquer-once]
version = "0.4.0"
default-features = false

[dependencies.object]
version = "0.32.2"
features = ["read_core", "elf"]
default-features = false

[dependencies.noto-sans-mono-bitmap]
version = "0.2.0"
features = ["bold", "size_16", "unicode-basic-latin"]
default-features = false
