cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
forced-target = "x86_64-unknown-none"

[dependencies]
x86_64 = "0.15.2"
spin = "0.9.8"
uart_16550 = "0.3.2"
pc-keyboard = "0.8.0"
acpi = "5.1.0"
x2apic = "0.4.3"
bitflags = "2.6.0"
good_memory_allocator = "0.1.7"
bit_field = "0.10.2"
limine = "0.3.1"
xhci = "0.9.2"
pci_types = "0.10.0"
vcell = "0.1.3"
nvme = "0.1.2"
derive-where = "1.2.7"
humansize = "2.1.3"

[dependencies.time]
version = "0.3.37"
default-features = false

[dependencies.thiserror]
version = "2.0.4"
default-features = false

[dependencies.os-terminal]
version = "0.5.4"
features = ["truetype"]
default-features = false

[dependencies.crossbeam-queue]
version = "0.3.11"
features = ["alloc"]
default-features = false

[dependencies.object]
version = "0.36.5"
features = ["read_core", "elf", "unaligned"]
default-features = false

[dependencies.log]
version = "0.4.22"
default-features = false
