[package]
name = "builder"
edition = "2021"
version = "0.1.0"

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
argh = "0.1.10"

[dependencies.bootloader]
version = "0.11.7"
features = ["uefi"]
default-features = false

[dependencies.kernel]
path = "../kernel"
artifact = "bin"
target = "x86_64-unknown-none"
