[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.11"
ovmf-prebuilt = "0.1.0-alpha.1"

[dependencies.TrashOS]
path = ".."
artifact = "bin"
target = "x86_64-unknown-none"
